"""Create/adopt the FairShare application schema.

This is the canonical application migration. It is intentionally written to be
idempotent enough to adopt the existing FairShare Supabase database while also
creating the same application schema in a fresh PostgreSQL database.
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def table_exists(bind, table: str) -> bool:
    return sa.inspect(bind).has_table(table, schema="public")


def column_exists(bind, table: str, column: str) -> bool:
    return any(col["name"] == column for col in sa.inspect(bind).get_columns(table, schema="public"))


def index_exists(bind, table: str, name: str) -> bool:
    return any(idx.get("name") == name for idx in sa.inspect(bind).get_indexes(table, schema="public"))


def unique_exists(bind, table: str, name: str) -> bool:
    return any(item.get("name") == name for item in sa.inspect(bind).get_unique_constraints(table, schema="public"))


def check_exists(bind, table: str, name: str) -> bool:
    return any(item.get("name") == name for item in sa.inspect(bind).get_check_constraints(table, schema="public"))


def has_fk(bind, table: str, column: str, referent_table: str, referent_schema: str = "public") -> bool:
    for fk in sa.inspect(bind).get_foreign_keys(table, schema="public"):
        if column in (fk.get("constrained_columns") or []) and fk.get("referred_table") == referent_table and (fk.get("referred_schema") or "public") == referent_schema:
            return True
    return False


def upgrade() -> None:
    bind = op.get_bind()

    # Create the application-owned identity table without provider-specific
    # UUID defaults. UUIDs are generated by Python, which keeps the ORM portable.
    if not table_exists(bind, "users"):
        op.create_table(
            "users",
            sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
            sa.Column("email", sa.String(320), nullable=True),
            sa.Column("full_name", sa.String(120), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
            schema="public",
        )

    if not table_exists(bind, "groups"):
        op.create_table(
            "groups",
            sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
            sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column("name", sa.String(80), nullable=False),
            sa.Column("type", sa.String(30), nullable=False, server_default="Trip"),
            sa.Column("currency", sa.String(3), nullable=False, server_default="INR"),
            sa.Column("description", sa.Text(), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
            schema="public",
        )

    if not table_exists(bind, "group_members"):
        op.create_table(
            "group_members",
            sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
            sa.Column("group_id", postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
            sa.Column("email", sa.String(320), nullable=False),
            sa.Column("role", sa.String(20), nullable=False, server_default="member"),
            sa.Column("status", sa.String(20), nullable=False, server_default="active"),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
            schema="public",
        )

    if not table_exists(bind, "expenses"):
        op.create_table(
            "expenses",
            sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
            sa.Column("group_id", postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column("title", sa.String(120), nullable=False),
            sa.Column("amount", sa.Numeric(14, 2), nullable=False),
            sa.Column("split_type", sa.String(20), nullable=False, server_default="Equal"),
            sa.Column("paid_by", postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
            schema="public",
        )

    if not table_exists(bind, "expense_splits"):
        op.create_table(
            "expense_splits",
            sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
            sa.Column("expense_id", postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column("amount", sa.Numeric(14, 2), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
            schema="public",
        )

    if not table_exists(bind, "settlements"):
        op.create_table(
            "settlements",
            sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
            sa.Column("group_id", postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column("from_user_id", postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column("to_user_id", postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column("amount", sa.Numeric(14, 2), nullable=False),
            sa.Column("note", sa.Text(), nullable=True),
            sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
            schema="public",
        )

    bind = op.get_bind()
    if not column_exists(bind, "expenses", "split_type"):
        op.add_column("expenses", sa.Column("split_type", sa.String(20), nullable=False, server_default="Equal"), schema="public")
    if not column_exists(bind, "group_members", "status"):
        op.add_column("group_members", sa.Column("status", sa.String(20), nullable=False, server_default="active"), schema="public")

    # Build the user registry from whatever already exists. This is deliberately
    # conditional so a fresh PostgreSQL database without Supabase Auth also works.
    op.execute("""
        INSERT INTO public.users (id, email, full_name)
        SELECT DISTINCT ON (x.id) x.id, x.email, x.full_name
        FROM (
            SELECT gm.user_id AS id, lower(gm.email) AS email, NULL::text AS full_name
            FROM public.group_members gm
            WHERE gm.user_id IS NOT NULL
            UNION ALL
            SELECT e.paid_by AS id, NULL::text, NULL::text
            FROM public.expenses e
            WHERE e.paid_by IS NOT NULL
            UNION ALL
            SELECT es.user_id AS id, NULL::text, NULL::text
            FROM public.expense_splits es
            WHERE es.user_id IS NOT NULL
            UNION ALL
            SELECT s.from_user_id AS id, NULL::text, NULL::text
            FROM public.settlements s
            WHERE s.from_user_id IS NOT NULL
            UNION ALL
            SELECT s.to_user_id AS id, NULL::text, NULL::text
            FROM public.settlements s
            WHERE s.to_user_id IS NOT NULL
            UNION ALL
            SELECT s.created_by AS id, NULL::text, NULL::text
            FROM public.settlements s
            WHERE s.created_by IS NOT NULL
        ) x
        WHERE x.id IS NOT NULL
        ON CONFLICT (id) DO UPDATE SET
            email = COALESCE(public.users.email, EXCLUDED.email),
            full_name = COALESCE(public.users.full_name, EXCLUDED.full_name)
    """)

    op.execute("""
        DO $$
        BEGIN
            IF to_regclass('auth.users') IS NOT NULL THEN
                INSERT INTO public.users (id, email, full_name)
                SELECT u.id, lower(u.email), NULLIF(trim(u.raw_user_meta_data ->> 'full_name'), '')
                FROM auth.users u
                ON CONFLICT (id) DO UPDATE SET
                    email = COALESCE(EXCLUDED.email, public.users.email),
                    full_name = COALESCE(EXCLUDED.full_name, public.users.full_name);
            END IF;
        END $$;
    """)

    op.execute("""
        DO $$
        BEGIN
            IF to_regclass('public.profiles') IS NOT NULL THEN
                UPDATE public.users u
                SET full_name = COALESCE(NULLIF(trim(p.full_name), ''), u.full_name)
                FROM public.profiles p
                WHERE p.id = u.id;
            END IF;
        END $$;
    """)

    # Make duplicate identities deterministic before adding the portable
    # per-group uniqueness constraint.
    op.execute("""
        DELETE FROM public.group_members a
        USING public.group_members b
        WHERE a.id > b.id
          AND a.user_id IS NOT NULL
          AND a.group_id = b.group_id
          AND a.user_id = b.user_id;
    """)

    # Decouple application FKs from Supabase Auth. The same UUIDs are retained.
    op.execute("""
        DO $$
        DECLARE r record;
        BEGIN
            IF to_regclass('auth.users') IS NOT NULL THEN
                FOR r IN
                    SELECT con.conname, cls.relname
                    FROM pg_constraint con
                    JOIN pg_class cls ON cls.oid = con.conrelid
                    JOIN pg_namespace nsp ON nsp.oid = cls.relnamespace
                    WHERE con.contype = 'f'
                      AND nsp.nspname = 'public'
                      AND cls.relname IN ('groups','group_members','expenses','expense_splits','settlements')
                      AND con.confrelid = 'auth.users'::regclass
                LOOP
                    EXECUTE format('ALTER TABLE public.%I DROP CONSTRAINT %I', r.relname, r.conname);
                END LOOP;
            END IF;
        END $$;
    """)

    bind = op.get_bind()
    fk_specs = [
        ("groups", "owner_id", "users", "id", "fk_groups_owner_users", "CASCADE"),
        ("group_members", "group_id", "groups", "id", "fk_group_members_group_groups", "CASCADE"),
        ("group_members", "user_id", "users", "id", "fk_group_members_user_users", "CASCADE"),
        ("expenses", "group_id", "groups", "id", "fk_expenses_group_groups", "CASCADE"),
        ("expenses", "paid_by", "users", "id", "fk_expenses_payer_users", "CASCADE"),
        ("expense_splits", "expense_id", "expenses", "id", "fk_expense_splits_expense", "CASCADE"),
        ("expense_splits", "user_id", "users", "id", "fk_expense_splits_user_users", "CASCADE"),
        ("settlements", "group_id", "groups", "id", "fk_settlements_group_groups", "CASCADE"),
        ("settlements", "from_user_id", "users", "id", "fk_settlements_from_users", "CASCADE"),
        ("settlements", "to_user_id", "users", "id", "fk_settlements_to_users", "CASCADE"),
        ("settlements", "created_by", "users", "id", "fk_settlements_created_by_users", "SET NULL"),
    ]
    for table, col, target, target_col, name, ondelete in fk_specs:
        if not has_fk(bind, table, col, target):
            op.create_foreign_key(name, table, target, [col], [target_col], source_schema="public", referent_schema="public", ondelete=ondelete)

    # Normalize legacy data to the supported application values.
    op.execute("UPDATE public.group_members SET email = lower(trim(email)) WHERE email IS NOT NULL")
    op.execute("""
        DELETE FROM public.group_members a
        USING public.group_members b
        WHERE a.id > b.id
          AND a.group_id = b.group_id
          AND lower(trim(a.email)) = lower(trim(b.email));
    """)
    op.execute("UPDATE public.users SET email = lower(trim(email)) WHERE email IS NOT NULL AND trim(email) <> ''")
    op.execute("""
        WITH ranked AS (
            SELECT id, row_number() OVER (PARTITION BY lower(email) ORDER BY created_at, id) AS rn
            FROM public.users
            WHERE email IS NOT NULL AND trim(email) <> ''
        )
        UPDATE public.users u
        SET email = NULL
        FROM ranked r
        WHERE u.id = r.id AND r.rn > 1;
    """)
    op.execute("UPDATE public.group_members SET role = 'member' WHERE role IS NULL OR lower(role) NOT IN ('owner','admin','member','viewer')")
    op.execute("UPDATE public.group_members SET role = lower(role)")
    op.execute("UPDATE public.group_members SET status = 'active' WHERE status IS NULL OR lower(status) NOT IN ('pending','active')")
    op.execute("UPDATE public.group_members SET status = lower(status)")
    op.execute("UPDATE public.expenses SET split_type = 'Equal' WHERE split_type IS NULL OR split_type NOT IN ('Equal','Exact','Percentage','Shares')")
    op.execute("UPDATE public.groups SET type = 'Other' WHERE type IS NULL OR type NOT IN ('Trip','Home','Friends','Office','Other')")
    op.execute("UPDATE public.groups SET currency = upper(COALESCE(NULLIF(trim(currency), ''), 'INR'))")
    op.execute("UPDATE public.groups SET currency = 'INR' WHERE length(currency) <> 3 OR currency !~ '^[A-Z]{3}$'")

    # Ensure every owner is also an active member.
    op.execute("""
        INSERT INTO public.group_members (id, group_id, user_id, email, role, status)
        SELECT (md5(g.id::text || g.owner_id::text || 'owner')::uuid), g.id, g.owner_id, COALESCE(u.email, 'owner-' || g.owner_id::text || '@local.invalid'), 'owner', 'active'
        FROM public.groups g
        LEFT JOIN public.users u ON u.id = g.owner_id
        WHERE NOT EXISTS (
            SELECT 1 FROM public.group_members gm WHERE gm.group_id = g.id AND gm.user_id = g.owner_id
        )
    """)

    bind = op.get_bind()
    if not unique_exists(bind, "users", "uq_users_email"):
        op.create_unique_constraint("uq_users_email", "users", ["email"], schema="public")
    if not unique_exists(bind, "group_members", "uq_group_members_group_email"):
        op.create_unique_constraint("uq_group_members_group_email", "group_members", ["group_id", "email"], schema="public")
    if not unique_exists(bind, "group_members", "uq_group_members_group_user"):
        op.create_unique_constraint("uq_group_members_group_user", "group_members", ["group_id", "user_id"], schema="public")
    if not unique_exists(bind, "expense_splits", "uq_expense_splits_expense_user"):
        op.create_unique_constraint("uq_expense_splits_expense_user", "expense_splits", ["expense_id", "user_id"], schema="public")

    check_specs = [
        ("ck_groups_type", "groups", "type IN ('Trip', 'Home', 'Friends', 'Office', 'Other')"),
        ("ck_groups_currency_length", "groups", "length(currency) = 3 AND currency ~ '^[A-Z]{3}$'"),
        ("ck_group_members_role", "group_members", "role IN ('owner', 'admin', 'member', 'viewer')"),
        ("ck_group_members_status", "group_members", "status IN ('pending', 'active')"),
        ("ck_expenses_amount_positive", "expenses", "amount > 0"),
        ("ck_expenses_split_type", "expenses", "split_type IN ('Equal', 'Exact', 'Percentage', 'Shares')"),
        ("ck_expense_splits_amount_nonnegative", "expense_splits", "amount >= 0"),
        ("ck_settlements_amount_positive", "settlements", "amount > 0"),
        ("ck_settlements_different_users", "settlements", "from_user_id <> to_user_id"),
    ]
    bind = op.get_bind()
    for name, table, expression in check_specs:
        if not check_exists(bind, table, name):
            op.create_check_constraint(name, table, expression, schema="public")

    index_specs = [
        ("ix_groups_owner_created", "groups", ["owner_id", "created_at"]),
        ("ix_group_members_group_created", "group_members", ["group_id", "created_at"]),
        ("ix_group_members_user", "group_members", ["user_id"]),
        ("ix_expenses_group_created", "expenses", ["group_id", "created_at"]),
        ("ix_expenses_paid_by", "expenses", ["paid_by"]),
        ("ix_expense_splits_expense", "expense_splits", ["expense_id"]),
        ("ix_expense_splits_user", "expense_splits", ["user_id"]),
        ("ix_settlements_group_created", "settlements", ["group_id", "created_at"]),
        ("ix_settlements_group_from", "settlements", ["group_id", "from_user_id"]),
        ("ix_settlements_group_to", "settlements", ["group_id", "to_user_id"]),
    ]
    bind = op.get_bind()
    for name, table, columns in index_specs:
        if not index_exists(bind, table, name):
            op.create_index(name, table, columns, schema="public")

    # Prevent the Supabase PostgREST roles from being the application's data API.
    # The backend connects with a DB credential and remains the application data boundary.
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
                REVOKE ALL ON public.users, public.groups, public.group_members, public.expenses, public.expense_splits, public.settlements FROM anon;
            END IF;
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
                REVOKE ALL ON public.users, public.groups, public.group_members, public.expenses, public.expense_splits, public.settlements FROM authenticated;
            END IF;
        END $$;
    """)


def downgrade() -> None:
    # This revision adopts an existing database and intentionally does not
    # implement destructive rollback of application data.
    pass
