import React,{useState} from 'react';
import {SafeAreaView,ScrollView,Text,TextInput,StyleSheet,Pressable,Alert,View,ActivityIndicator} from 'react-native';
import {useNavigation} from '@react-navigation/native';
import {signUp} from '../../services/authService';
export default function SignUpScreen(){
 const nav=useNavigation<any>();const[n,setN]=useState('');const[e,setE]=useState('');const[p,setP]=useState('');const[c,setC]=useState('');const[sp,setSP]=useState(false);const[sc,setSC]=useState(false);const[l,setL]=useState(false);
 const create=async()=>{if(!n.trim())return Alert.alert('Error','Enter your name');if(!/^\S+@\S+\.\S+$/.test(e))return Alert.alert('Error','Enter a valid email');if(p.length<8)return Alert.alert('Error','Password must be at least 8 characters');if(p!==c)return Alert.alert('Error','Passwords do not match');setL(true);const{error}=await signUp(e,p);setL(false);if(error)return Alert.alert('Sign Up Failed',error.message);Alert.alert('Success','Account created. Check your email for verification.',[{text:'OK',onPress:()=>nav.navigate('Login')}]);};
 return <SafeAreaView style={s.c}><ScrollView contentContainerStyle={s.cc}><Text style={s.t}>Create Account</Text><TextInput style={s.i} placeholder='Full Name' placeholderTextColor='#94A3B8' value={n} onChangeText={setN}/><TextInput style={s.i} placeholder='Email' placeholderTextColor='#94A3B8' autoCapitalize='none' value={e} onChangeText={setE}/><View style={s.pb}><TextInput style={s.pi} placeholder='Password' placeholderTextColor='#94A3B8' secureTextEntry={!sp} value={p} onChangeText={setP}/><Pressable onPress={()=>setSP(!sp)}><Text style={s.lk}>{sp?'Hide':'Show'}</Text></Pressable></View><View style={s.pb}><TextInput style={s.pi} placeholder='Confirm Password' placeholderTextColor='#94A3B8' secureTextEntry={!sc} value={c} onChangeText={setC}/><Pressable onPress={()=>setSC(!sc)}><Text style={s.lk}>{sc?'Hide':'Show'}</Text></Pressable></View><Pressable style={s.b} onPress={create} disabled={l}>{l?<ActivityIndicator color='white'/>:<Text style={s.bt}>Create Account</Text>}</Pressable><Pressable onPress={()=>nav.goBack()}><Text style={s.lk}>Already have an account? Sign In</Text></Pressable></ScrollView></SafeAreaView>}
 const s=StyleSheet.create({c:{flex:1,backgroundColor:'#0F172A'},cc:{flexGrow:1,padding:24,paddingBottom:60,justifyContent:'center'},t:{color:'white',fontSize:32,fontWeight:'700',marginBottom:24},i:{backgroundColor:'#1E293B',color:'white',padding:16,borderRadius:14,marginBottom:16},pb:{backgroundColor:'#1E293B',borderRadius:14,paddingHorizontal:16,flexDirection:'row',alignItems:'center',marginBottom:16},pi:{flex:1,color:'white',paddingVertical:16},b:{backgroundColor:'#0EA5A4',padding:16,borderRadius:14,alignItems:'center'},bt:{color:'white',fontWeight:'700'},lk:{color:'#0EA5A4',textAlign:'center',marginTop:20}});
